name: CI

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov

      - uses: ramsey/composer-install@v2

      - run: php vendor/bin/phpunit

      - run: cat var/junit.xml

      - run: php vendor/bin/infection --no-progress --coverage=var
